import gamefunctions
"""This file contains a main loop that consists of three options for players. The first option allows players
to fight a random monster. The random monster is generatetd by calling a function from gamefunctions.py.
The second option allows players to sleep and restore their HP for a cost of 5 gold. The third option allows 
players to quit the game. The main loop continues until the player chooses to quit or is defeated by a monster."""
player_hp = 100
player_gold = 50
player_name = input("What is your name? ")
gamefunctions.print_welcome(player_name, 25)

running = True

while running:
    """Main game loop that provides options for the player to fight a monster, sleep, or quit the game. 
    The loop continues until the player chooses to quit or is defeated by a monster."""
    print("You are in town.")
    print(f"Current HP: {player_hp}, Current Gold: {player_gold}")
    print("What would you like to do?\n")
    print("1) Leave town (Fight Monster)")
    print("2) Sleep (Restore HP for 5 Gold)")
    print("3) Quit")

    choice = input("> ")

    if choice == "1":
        """Option to fight a random monster. A random monster is generated by calling a function from gamefunctions.py.
        Thrre more functions are called from gamefunctions.py to display fight statistics, get the player's fight action, 
        and execute the fight action. The player can choose to attack or run away. If the player defeats the monster, 
        they receive gold. If the player is defeated, the game ends."""
        monster = gamefunctions.new_random_monster()
        print(f"\nA {monster['name']} appears!")
        print(monster["description"])
        while monster["health"] > 0 and player_hp > 0:
            gamefunctions.displayfightstatistics(player_hp, monster)
            action = gamefunctions.getUserFightAction()

            player_hp, player_gold, monster_dead, player_dead = \
                 gamefunctions.do_fight_action(action, player_hp, player_gold, monster)

        if monster_dead:
            print(f"\nYou defeated the {monster['name']} and found {monster['money']} gold!\n")
            player_gold += monster["money"]
    
        if player_dead:
            print("\nYou have been defeated. Game Over.\n")
            running = False
           
    elif choice == "2":
        """Option to sleep and restore HP for a cost of 5 gold. If the player has enough gold,
        they can restore their HP by 20 points, up to a maximum of 100 HP. If the player does 
        not have enough gold, a message is printed."""
        if player_gold >= 5:
            player_gold -= 5
            if player_hp < 80:
                player_hp += 20
            else:
                player_hp = 100
                
            print("\nYou sleep and restore your HP.\n")
        else:
            print("\nYou don't have enough gold.\n")
    elif choice == "3":
        """Option to quit the game. A goodbye message is printed and the main loop ends."""
        print("\nGoodbye!")
        running = False
    else:
        print("\nTry another option!\n")
